In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("stephanmatzka/predictive-maintenance-dataset-ai4i-2020")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'predictive-maintenance-dataset-ai4i-2020' dataset.
Path to dataset files: /kaggle/input/predictive-maintenance-dataset-ai4i-2020

In [2]:
import pandas as pd
import os

root_dir=os.path.join(path,"ai4i2020.csv")

df=pd.read_csv(root_dir)

df

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [ ]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.6.17)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 2.7 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 11.0 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 19.9 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 29.8 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.0 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.5 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

In [4]:
from ydata_profiling import ProfileReport

profile=ProfileReport(df,title="Predictive Maintenance_ydata")

profile.to_file("Predictive Maintenance_ydata.html")

# os.path.abspath("Predictive Maintenance_ydata")

/tmp/ipykernel_4003/2013571452.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]
 14%|█▍        | 2/14 [00:00<00:03,  3.61it/s]
 57%|█████▋    | 8/14 [00:00<00:00, 14.57it/s]
100%|██████████| 14/14 [00:00<00:00, 14.71it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

In [6]:
df.drop(columns=['UDI','Product ID','TWF','HDF','PWF','OSF','RNF'], inplace=True)

In [7]:
df.rename(columns={'Air temperature [K]':'Air temperature', 'Process temperature [K]':'Process temperature', 'Rotational speed [rpm]' : 'Rotational speed', 'Torque [Nm]':'Torque', 'Tool wear [min]':'Tool wear'},inplace=True)

In [8]:
df

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0
...,...,...,...,...,...,...,...
9995,M,298.8,308.4,1604,29.5,14,0
9996,H,298.9,308.4,1632,31.8,17,0
9997,M,299.0,308.6,1645,33.4,22,0
9998,H,299.0,308.7,1408,48.5,25,0
9999,M,299.0,308.7,1500,40.2,30,0

In [9]:
df.dtypes

Type                    object
Air temperature        float64
Process temperature    float64
Rotational speed         int64
Torque                 float64
Tool wear                int64
Machine failure          int64
dtype: object

In [10]:
cate_col=[]
num_col=[]
def num_obj_col(df):
  for column in df:

    if df[column].dtypes == "object":
      # print(column,df[column].unique())
      cate_col.append(column)

    else:
      num_col.append(column)

num_obj_col(df)

print(cate_col)
print(num_col)

['Type']
['Air temperature', 'Process temperature', 'Rotational speed', 'Torque', 'Tool wear', 'Machine failure']

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Type'] = le.fit_transform(df['Type'])

In [12]:
df

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure
0,2,298.1,308.6,1551,42.8,0,0
1,1,298.2,308.7,1408,46.3,3,0
2,1,298.1,308.5,1498,49.4,5,0
3,1,298.2,308.6,1433,39.5,7,0
4,1,298.2,308.7,1408,40.0,9,0
...,...,...,...,...,...,...,...
9995,2,298.8,308.4,1604,29.5,14,0
9996,0,298.9,308.4,1632,31.8,17,0
9997,2,299.0,308.6,1645,33.4,22,0
9998,0,299.0,308.7,1408,48.5,25,0
9999,2,299.0,308.7,1500,40.2,30,0

In [13]:
X=df.drop(columns='Machine failure')
y=df['Machine failure']

In [14]:
X.shape

(10000, 6)

In [15]:
y.shape

(10000,)

In [16]:
y.value_counts()

Machine failure
0    9661
1     339
Name: count, dtype: int64

## **Multiple model**

In [17]:
# from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
import pickle
import os


def multiple_model(X_train, y_train, X_test, y_test):

    # logistic regression
    log_reg = LogisticRegression(max_iter=1000, random_state=42)

    # random forest
    rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)

    # xgboost
    xgb = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42, eval_metric='logloss')

    # Voting
    ensemble = VotingClassifier(
        estimators=[
            ('lr', log_reg),
            ('rf', rf),
            ('xgb', xgb)
        ],
        voting='soft'
    )


    models = {
        'Logistic Regression': log_reg,
        'Random Forest': rf,
        'XGBoost': xgb,
        'Ensemble (Voting)': ensemble
    }




    best_accuracy = 0
    best_model_name = ""
    trained_models= {}

    print("--- Model Training and Evaluation --- \n")

    for name, model in models.items():


        # model
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)

        print(f"{name} Accuracy: {acc:.4f}")

        print("Classification Report: \n", classification_report(y_test, y_pred))


        trained_models[name] = model
        if acc > best_accuracy:
            best_accuracy = acc
            best_model_name = name

    print(f"\n🏆 Best Model: {best_model_name} with Accuracy: {best_accuracy:.4f}")


    os.makedirs("model", exist_ok=True)

    # Extract your highest performing model from the tracking dictionary
    best_model_object = trained_models[best_model_name]

    # Correctly pass BOTH the model object and the file handler to pickle
    with open("model/model.pkl", "wb") as file:
        pickle.dump(best_model_object, file)
        print(f"📦 Best Model ({best_model_name}) saved successfully as 'model/model.pkl'!")

    # return trained_models

## **X and y are imbalance**

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10, stratify=y)
multiple_model(X_train, y_train, X_test, y_test)

--- Model Training and Evaluation ---

Logistic Regression Accuracy: 0.9695
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98      1932
           1       0.68      0.19      0.30        68

    accuracy                           0.97      2000
   macro avg       0.83      0.59      0.64      2000
weighted avg       0.96      0.97      0.96      2000

Random Forest Accuracy: 0.9845
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.89      0.62      0.73        68

    accuracy                           0.98      2000
   macro avg       0.94      0.81      0.86      2000
weighted avg       0.98      0.98      0.98      2000

XGBoost Accuracy: 0.9865
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.89      0.69      0.78        68

    accuracy                           0.99      2000
   macro avg       0.94      0.84      0.88      2000
weighted avg       0.99      0.99      0.99      2000

Ensemble (Voting) Accuracy: 0.9850
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.91      0.62      0.74        68

    accuracy                           0.98      2000
   macro avg       0.95      0.81      0.86      2000
weighted avg       0.98      0.98      0.98      2000


🏆 Best Model: XGBoost with Accuracy: 0.9865
📦 Best Model (XGBoost) saved successfully as 'model/model.pkl'!

## **imbalance data handle**

**SMOTE**

In [19]:
from imblearn.over_sampling import SMOTE
from collections import Counter

smote=SMOTE(random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10, stratify=y)

X_smote, y_smote = smote.fit_resample(X_train, y_train)
print("\n applying SMOTE then:", Counter(y_smote))

 applying SMOTE then: Counter({0: 7729, 1: 7729})

In [20]:
multiple_model(X_smote, y_smote, X_test, y_test)

--- Model Training and Evaluation ---

Logistic Regression Accuracy: 0.8340
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.83      0.91      1932
           1       0.15      0.82      0.25        68

    accuracy                           0.83      2000
   macro avg       0.57      0.83      0.58      2000
weighted avg       0.96      0.83      0.88      2000

Random Forest Accuracy: 0.9455
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.95      0.97      1932
           1       0.37      0.87      0.52        68

    accuracy                           0.95      2000
   macro avg       0.68      0.91      0.75      2000
weighted avg       0.97      0.95      0.96      2000

XGBoost Accuracy: 0.9615
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98      1932
           1       0.47      0.88      0.61        68

    accuracy                           0.96      2000
   macro avg       0.73      0.92      0.79      2000
weighted avg       0.98      0.96      0.97      2000

Ensemble (Voting) Accuracy: 0.9490
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.95      0.97      1932
           1       0.39      0.85      0.53        68

    accuracy                           0.95      2000
   macro avg       0.69      0.90      0.75      2000
weighted avg       0.97      0.95      0.96      2000


🏆 Best Model: XGBoost with Accuracy: 0.9615
📦 Best Model (XGBoost) saved successfully as 'model/model.pkl'!

# **class weights**

In [48]:
from sklearn.model_selection import GridSearchCV
def class_weights(X_train, y_train, X_test, y_test):
    negative_cases = np.sum(y_train == 0)
    positive_cases = np.sum(y_train == 1)
    weight = negative_cases / positive_cases

    print(f"Calculated scale_pos_weight: {weight:.2f}")
    print("Hyperparameter Tuning start..... waiting...\n")

    # Base Model
    base_model = xgb.XGBClassifier(scale_pos_weight=weight, random_state=42, eval_metric='logloss')

    # parameter tuining
    param_grid = {
        'n_estimators': [100, 200, 300],
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1, 0.2]
    }

    # GridSearchCV
    grid_search = GridSearchCV(
        estimator=base_model,
        param_grid=param_grid,
        scoring='f1',
        cv=3,
        verbose=1,
        n_jobs=-1
    )

    # model training
    grid_search.fit(X_train, y_train)

    print("\nTraining completed")
    print(f"best parameter: {grid_search.best_params_}\n")

    # Best Estimator
    best_model = grid_search.best_estimator_

    # prediction and evalution
    y_pred = best_model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    print(f" Accuracy: {acc:.4f}")

    print("--- Tuned Confusion Matrix ---")
    print(confusion_matrix(y_test, y_pred))

    print("\n--- Tuned Classification Report ---")
    print(classification_report(y_test, y_pred))

    # save model
    os.makedirs("model", exist_ok=True)
    with open("model/model.pkl", "wb") as file:
        pickle.dump(best_model, file)
        print("📦 Tuned Best Model saved successfully as 'model/tuned_xgboost_model.pkl'!")

In [49]:
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

class_weights(X_train, y_train, X_test, y_test)

Calculated scale_pos_weight: 27.78
Hyperparameter Tuning start..... waiting...

Fitting 3 folds for each of 27 candidates, totalling 81 fits

Training completed
best parameter: {'learning_rate': 0.2, 'max_depth': 7, 'n_estimators': 300}

 Accuracy: 0.9820
--- Tuned Confusion Matrix ---
[[1921   18]
 [  18   43]]

--- Tuned Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1939
           1       0.70      0.70      0.70        61

    accuracy                           0.98      2000
   macro avg       0.85      0.85      0.85      2000
weighted avg       0.98      0.98      0.98      2000

📦 Tuned Best Model saved successfully as 'model/tuned_xgboost_model.pkl'!

## **Testing**